services:
  dotfiles-test-ubuntu:
    build:
      context: ../
      dockerfile: base-ubuntu/Dockerfile.test
      args:
        UID: ${UID:-1000}
        GID: ${GROUPS:-1000}
        USERNAME: testuser
        GROUPNAME: testuser
    image: dotfiles-test-ubuntu:latest
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ../..:/home/testuser/dotfiles
    working_dir: /home/testuser/dotfiles
    user: testuser
