# vim: set expandtab ts=2 fenc=utf-8 ff=unix filetype=sh :

umask 022

# EDITOR設定
# ---

if which vim > /dev/null 2>&1 ; then
  export EDITOR=vim
else
  export EDITOR=vi
fi

# 標準入力端末時にctrl-sによる出力ロックを無効化
# ---

if [[ -t 0 ]]; then
  stty stop undef
fi

# WSL用 DISPLAY設定(最新では不要)
# ---

#if [[ -v WSL_DISTRO_NAME ]]; then
#if uname --kernel-release | grep -q -e "WSL" &> /dev/null && [[ ! -v DISPLAY ]]; then
#  export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
#fi

# HOME以外から開始する場合にディレクトリスタックにHOMEを追加
# ---

if [[ ! "${PWD}" = "${HOME}" ]]; then
  pushd -n "${HOME}" &> /dev/null
fi

# fcitxを自動的にONにする設定
# ---
# 2022-01-25 コメントアウト

#export DISPLAY=localhost:0.0

#export GTK_IM_MODULE=fcitx
#export QT_IM_MODULE=fcitx
#export XMODIFIERS=@im=fcitx
#export DefaultIMModule=fcitx
## fcitx-autostart
#if xset -q > /dev/null 2>&1; then
# xset -r 49
#fi

#

# PATH変数に同じ内容があった場合削除して先頭に移動の関数定義
# ---

__add_front_mypath () {
  export PATH="$(
    declare -A paths
    echo -n "${1}";
    #echo "${1}";
    paths["${1}"]=1
    echo "${PATH}:" | while IFS= read -d ':' -r p; do
      if [[ -v paths["${p}"] ]]; then
        continue;
      fi;
      echo -n ":${p}";
      #echo ":${p}";
      paths["${p}"]=1
      #declare -p paths
    done;
  )"
}

# サブ読み込み
# ---

#source $(dirname "${BASH_SOURCE}")/aliasrc.sh 
#source $(dirname "${BASH_SOURCE}")/utils.sh

if [[ -d "$(dirname "${BASH_SOURCE:-$0}")/bashrc.d" ]]; then
  for conf in "$(dirname "${BASH_SOURCE:-$0}")/bashrc.d"/*.bash; do
    if [[ -r "$conf" ]]; then
      echo "source bashrc.d $conf"
      source "$conf"
    fi
  done

  for conf in "$(dirname "${BASH_SOURCE:-$0}")/bashrc.d/"*.d/*; do
    if [[ -r "$conf" ]]; then
      echo "source bashrc.d/*.d $conf"
      source "$conf"
    fi
  done

  unset conf
fi

