" vim : set ts=2 sw=2 et filetype=vim :

" 初期設定

set nocompatible

unlet! skip_defaults_vim
source $VIMRUNTIME/defaults.vim

" ランタイムパス

let s:my_runtimepath = empty($XDG_CONFIG_HOME) ?
                                \ expand($XDG_CONFIG_HOME . '/vim') :
                                \ expand('$HOME/.config/vim')

"if isdirectory(s:my_runtimepath)
"  let &runtimepath=s:my_runtimepath
"                      \ . ',' . &runtimepath
"                      \ . ',' . s:my_runtimepath . "/after"
"endif

" 文字コード設定

set encoding=utf-8
scriptencoding utf-8

" 画面
syntax enable

if filereadable(expand(s:my_runtimepath . 'colors/solarized.vim'))

  if has('gui_running')
    set background=light
  else
    set background=dark
  endif

  colorscheme solarized
  "let g:solarized_termcolors=256

else

  colorscheme desert

endif

set number
set cmdheight=2

set laststatus=2
set cursorline
set cursorcolumn
set display=lastline

set visualbell

" 編集
set ts=2
set expandtab
set shiftwidth=2

set autoindent
set smartindent

" 移動

nnoremap <C-j> <C-w>w
nnoremap <C-k> <C-w>W
nnoremap <C-l> gt
nnoremap <C-h> gT

" バッファ

set hidden

