#!/bin/bash

umask 022

export PATH=$PATH:$HOME/usr/bin:$HOME/usr/local/bin

PS1='\[\e]0;\u@\h: \w\a\]\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}[$(dirs)]\n\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\][[\w]]\[\033[00m\]\n\$ '

if which vim > /dev/null 2>&1 ; then
  export EDITOR=vim
else
  export EDITOR=vi
fi

if [[ -v WSL_DISTRO_NAME ]]; then
  export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0
fi

# 標準入力端末時にctrl-sによる出力ロックを無効化
if [[ -t 0 ]]; then
  stty stop undef
fi

export HISTCONTROL=ignoreboth
export HISTSIZE=65535
export HISTFILESIZE=65535
export HISTIGNORE="history*:p[0-9n]:jobs"

# 履歴重複削除
function share_history {
	history -a &&
	tac ~/.bash_history |
	awk '!a[$0]++' |
	tac > ~/.bash_history.tmp &&
	[ -f ~/.bash_history.tmp ] &&
	mv ~/.bash_history{.tmp,} &&
	history -c &&
	history -r
}

PROMPT_COMMAND='share_history'
shopt -u histappend

#

if [[ ! "${PWD}" = "${HOME}" ]]; then
  pushd -n "${HOME}"
fi

#

source $(dirname "${BASH_SOURCE}")/aliasrc.sh 
source $(dirname "${BASH_SOURCE}")/utils.sh

